version: '3.1'

services:
  redis:
    image: "redis:latest"
    restart: always
    container_name: redis
    ports: 
      - "6379:6379"

  db:
    build:
      context: .
      dockerfile: Dockerfile-pg
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=credAdmin
      - POSTGRES_PASSWORD=Test1234@
      - POSTGRES_DB=credstore
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/mysql/data
  
  rabbit:
    image: "rabbitmq:3-management"
    restart: always
    container_name: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbithole"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"

  credstore:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "db"
      - "redis"
      - "rabbit"
    container_name: credstore
    environment:
      - MQ_HOST=rabbit
      - MQ_PORT=5672
      - MQ_USER=rabbitmq
      - MQ_PASSWORD=rabbithole
      - PG_HOST=postgres
      - PG_USER=credadmin
      - PG_PASSWORD=Test1234@
      - PG_DBNAME=credstore
      - PG_PORT=5432
      - REDIS_ADDR=redis:6379
      - REDIS_CH=result

volumes:
  db-data:
